---
# -- (Optional) When using a custom network
# networks:
#   proxy:
#     external: true
services:
  twingate_connector:
    container_name: twingate_techhivehq
    image: docker.io/twingate/connector:latest
    environment:
      - TWINGATE_NETWORK=techhivehq
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN} # TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN} # TWINGATE_REFRESH_TOKEN
      # -- (Optional) Change loglevel
      # - TWINGATE_LOG_LEVEL=3
      # -- (Optional) Add custom DNS Server
      # - TWINGATE_DNS=10.20.0.1
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    # -- (Optional) When using a custom network
    # networks:
    #   - proxy
    restart: unless-stopped