---
services:
  code:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ= # add your time zone
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.yourdomain.com #optional # Change to your domain name
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - /home/user/docker_volumes/code-server/config:/config # Change to your path and leave :/config as it is
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.entrypoints=http"
      - "traefik.http.routers.code.rule=Host(`code-server.yourdomain.com`)"   # Change to your domain name
      - "traefik.http.middlewares.code-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.code.middlewares=code-https-redirect"
      - "traefik.http.routers.code-secure.entrypoints=https"
      - "traefik.http.routers.code-secure.rule=Host(`code-server.yourdomain.com`)"  # Change to your domain name
      - "traefik.http.routers.code-secure.tls=true"
      - "traefik.http.routers.code-secure.service=code"
      - "traefik.http.services.code.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true