---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Hypervisor:
    - Proxmox-VE:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Proxmox VE
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
            node: node name # optional

    - Proxmox-PBS:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_PBS_URL}}"
        description: Proxmox Backup Server
        widget:
            type: proxmoxbackupserver
            url: "{{HOMEPAGE_VAR_PROXMOX_PBS_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_PBS_USER}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_PBS_API_KEY}}"

    - TrueNAS:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        description: TrueNAS Scale
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"

- Data:
    - Nextcloud:
        icon: nextcloud.svg
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: Nextcloud
        widget:
            type: nextcloud
            url: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
            username: "{{HOMEPAGE_VAR_NEXTCLOUD_USER}}"
            password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"

    - Paperless:
        icon: paperless-ngx.svg
        href: "{{HOMEPAGE_VAR_PAPERLESS_URL}}"
        description: paperless-ngx
        widget:
            type: paperlessngx
            url: "{{HOMEPAGE_VAR_PAPERLESS_URL}}"
            username: "{{HOMEPAGE_VAR_PAPERLESS_USER}}"
            password: "{{HOMEPAGE_VAR_PAPERLESS_PASSWORD}}"

    - Stirling-PDF:
        icon: stirling-pdf.svg
        href: "{{HOMEPAGE_VAR_STIRLINGPDF_URL}}"
        description: Stiling-PDF

- Home-Automation:
    - Home Assistant:
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        description: Home
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"

    - Frigate:
        icon: frigate.svg
        href: "{{HOMEPAGE_VAR_FRIGATE_URL}}"
        description: NVR
        widget:
          type: frigate
          url: "{{HOMEPAGE_VAR_FRIGATE_URL}}"

    - Traefik:
        icon: traefik.svg
        href: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
        description: Traefik
        widget:
            type: traefik
            url: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
            username: "{{HOMEPAGE_VAR_TRAEFIK_USER}}"
            password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Jellyfin Media server

    - Plex:
        icon: plex.svg
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        description: plex media server

    - Open-webui:
        icon: open-webui.png
        href: "{{HOMEPAGE_VAR_OPEN_WEBUI_URL}}"
        description: Chat-AI

- Photos:
    - photoprism:
        icon: photoprism.svg
        href: "{{HOMEPAGE_VAR_PHOTOPRISM_URL}}"
        description: Photos
        widget:
            type: photoprism
            url: "{{HOMEPAGE_VAR_PHOTOPRISM_URL}}"
            username: "{{HOMEPAGE_VAR_PHOTOPRISM_USER}}"
            password: "{{HOMEPAGE_VAR_PHOTOPRISM_PASSWORD}}"

- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code

