---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: my Homepage # <----- add this line

background:
  image: 
#   image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
#   blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

theme: dark #or# light
color: stone
# Supported colors are: 
# slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan,
# sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white

layout:
  Home-Automation:
    header: false
    style: row
    columns: 3
  Hypervisor:
    header: false
    style: row
    columns: 3
  Data:
    header: false
    style: row
    columns: 3
  Media:
    header: false
    style: row
    columns: 3
  Photos:
    header: false
    style: row
    columns: 3
  Other:
    header: false
    style: row
    columns: 4

useEqualHeights: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# headerStyle: underlined # default style
# headerStyle: boxedWidgets
# headerStyle: boxed
headerStyle: clean

showStats: true